train: "/code/ResUnet/SIIM-ACR-Pneumothorax-Seg-XR/train"
valid: "/code/ResUnet/SIIM-ACR-Pneumothorax-Seg-XR/valid"
log: "logs"
logging_step: 100
validation_interval: 2000 # Save and valid have same interval
checkpoints: "checkpoints"

batch_size: 4
lr: 0.001
RESNET_PLUS_PLUS: True
IMAGE_SIZE: 1024
CROP_SIZE: 512